Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/medusa-2VgPi4zZ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
detector = SCRFDetector()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m detector [38;5;241m=[39m [43mSCRFDetector[49m[43m([49m[43m)[49m

File [0;32m~/work/medusa/medusa/medusa/detect/scrfd.py:55[0m, in [0;36mSCRFDetector.__init__[0;34m(self, det_size, det_threshold, nms_threshold, device)[0m
[1;32m     53[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m()
[1;32m     54[0m [38;5;28mself[39m[38;5;241m.[39mdet_size [38;5;241m=[39m det_size
[0;32m---> 55[0m [38;5;28mself[39m[38;5;241m.[39m_det_model [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_init_det_model[49m[43m([49m[43mdevice[49m[43m)[49m
[1;32m     56[0m [38;5;28mself[39m[38;5;241m.[39m_postproc_model [38;5;241m=[39m SCRFDPostproc(det_size, det_threshold, nms_threshold, device)
[1;32m     57[0m [38;5;28mself[39m[38;5;241m.[39mdevice [38;5;241m=[39m device

File [0;32m~/work/medusa/medusa/medusa/detect/scrfd.py:74[0m, in [0;36mSCRFDetector._init_det_model[0;34m(self, device)[0m
[1;32m     72[0m f_in [38;5;241m=[39m get_external_data_config([38;5;124m'[39m[38;5;124mbuffalo_path[39m[38;5;124m'[39m) [38;5;241m/[39m [38;5;124m'[39m[38;5;124mdet_10g.onnx[39m[38;5;124m'[39m
[1;32m     73[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m f_in[38;5;241m.[39mis_file():
[0;32m---> 74[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mCould not find model at [39m[38;5;132;01m{[39;00mf_in[38;5;132;01m}[39;00m[38;5;124m; run `medusa_download_external_data`[39m[38;5;124m"[39m)
[1;32m     76[0m output_shapes [38;5;241m=[39m []
[1;32m     77[0m [38;5;28;01mfor[39;00m n_feat [38;5;129;01min[39;00m [[38;5;241m1[39m, [38;5;241m4[39m, [38;5;241m10[39m]:  [38;5;66;03m# score, bbox, lms[39;00m

[0;31mValueError[0m: Could not find model at /home/runner/.medusa_ext_data/buffalo_l/det_10g.onnx; run `medusa_download_external_data`

